### ISSUE TITLE
fix slideshow images like czech

### ISSUE THREAD

**Issue by xtinarees** [xtinarees/Turn-The-Table#1]

**Comment by xtinarees** [comment]
@rickyferrer what do you think of giving slideshows a max-width so that on larger screens they are not full width. This would solve the problem of having to give images super big heights just so that they are proportional.

Example large screen: 
![screen shot 2016-01-16 at 5 16 51 pm](https://cloud.githubusercontent.com/assets/6852913/12374906/7370a6ec-bc71-11e5-868a-62b996fee30e.png)

Example small screen:
![screen shot 2016-01-16 at 5 20 02 pm](https://cloud.githubusercontent.com/assets/6852913/12374911/84b18322-bc71-11e5-895f-ae9a129ef5e7.png)

**Comment by rickyferrer** [comment]
I think this is a good solution. They are meeting this weekend and might have more changes. Let's see what they think about this.
