### ISSUE TITLE
add open table links

### ISSUE THREAD

**Issue by xtinarees** [xtinarees/Turn-The-Table#18]
For Dallas:
<div class="OTButton"><script type="text/javascript" src="https://secure.opentable.com/ism/link.aspx?rid=211069&restref=211069&bgimage=https://secure.opentable.com/img/frontDoor/ot_btn_red.png&hover=1"></script><noscript id="OT_noscript"><a href="http://www.opentable.com/smoke-reservations-dallas?rtype=ism&restref=211069" >Reserve Now On OpenTable.com</a></noscript><a id="OTPoweredBy" class="OTPoweredBy" href="http://www.opentable.com/smoke-reservations-dallas?rtype=ism&restref=211069" >Powered By OpenTable</a></div>

For Plano:
<div class="OTButton"><script type="text/javascript" src="https://secure.opentable.com/ism/link.aspx?rid=188344&restref=188344&bgimage=https://secure.opentable.com/img/frontDoor/ot_btn_red.png&hover=1"></script><noscript id="OT_noscript"><a href="http://www.opentable.com/smoke-reservations-plano?rtype=ism&restref=188344" >Reserve Now On OpenTable.com</a></noscript><a id="OTPoweredBy" class="OTPoweredBy" href="http://www.opentable.com/smoke-reservations-plano?rtype=ism&restref=188344" >Powered By OpenTable</a></div>

**Comment by rickyferrer** [comment]
could we get this up by the end of the day?

**Comment by xtinarees** [comment]
theodore link: http://www.opentable.com/the-theodore-reservations-dallas?restref=192121
