### ISSUE TITLE
add contact form 7 

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/Turn-The-Table#19]

**Comment by xtinarees** [comment]
@rickyferrer Should I add another menu item? 'contact'? or just stick the form below location?

**Comment by xtinarees** [comment]
Also, can you let me know what emails I should attach each one of these to? and should smokes' dallas/plano locations have the same form or different ones?

**Comment by rickyferrer** [comment]
Let's make it another menu item since location area is pretty full. We can do two columns. Left column will be name, email, phone fields. Right column will be comments, and submit button.

**Comment by rickyferrer** [comment]
For The Theodore, it would be info@thetheodore.com
For Smoke Dallas, it would be corey@smokerestaurant.com
For Smoke Plano, it would be katie@smokerestaurant.com
For Bolsa, it would be info@bolsadallas.com
For Bolsa Mercado, it would be justo@bolsadallas.com

**Comment by rickyferrer** [comment]
I installed Contact Form 7 on SMOKE site. I placed the shortcode into the custom field under location. But on the front end it puts the form on top of all the location info. Maybe you can look at this when you work on Bolsa.

**Comment by rickyferrer** [comment]
All Contact Forms have been built for all sites.
