### ISSUE TITLE
SMOKE: Mobile edit for landing page.

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/Turn-The-Table#28]
Place intro copy above book info:

> HONEST, GENUINE, & REAL
> Our food is locally and regionally sourced, made with integrity, and creates a sense of nostalgia. Food should bring a community to the table, and it is our goal to deliver an experience that is both authentic and down-home. Modern Texas Cuisine at its finest.

move book image above book copy.

**Comment by xtinarees** [comment]
@rickyferrer so only on mobile, not on desktop?

**Comment by rickyferrer** [comment]
Only on mobile
