### ISSUE TITLE
18px navigation w less padding

### ISSUE THREAD

**Issue by xtinarees** [xtinarees/Turn-The-Table#3]

**Comment by xtinarees** [comment]
@rickyferrer the navigation doesnt have padding. the nav items are spaced out evenly based on the width of the content. this allows the nav items to be flexible so that the template can accommodate different numbers of nav items without having to change the css for each scenario. I can make the container around the nav items smaller, which will make them look less spaced out, but then the nav container will not match up with the width of the rest of the site content. 

Larger container example:
![screen shot 2016-01-16 at 4 36 05 pm](https://cloud.githubusercontent.com/assets/6852913/12374750/99dbf5a8-bc6b-11e5-9650-ab3f1143d9e5.png)

Smaller container example:
![screen shot 2016-01-16 at 4 36 46 pm](https://cloud.githubusercontent.com/assets/6852913/12374752/a32174c6-bc6b-11e5-990a-dafac00713f2.png)

**Comment by rickyferrer** [comment]
I was referring to the height of the nav bar. With the smaller type, I'd like the height to be a little smaller as well. But again, let's wait to hear what the client's changes are first.
