### ISSUE TITLE
All sites: switch out Constant Contact with ZenDesk

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/Turn-The-Table#36]
`<script type="text/javascript" id="zr-57c711b0f4c47f000a94030f">

  (function() {

    (function () {

      function CustomEvent ( event, params ) {

        params = params || { bubbles: false, cancelable: false, detail: undefined };

        var evt = document.createEvent('CustomEvent');

        evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );

        return evt;

      }

      CustomEvent.prototype = window.Event.prototype;

      window.CustomEvent = CustomEvent;

    })();

    window.zrPopover = new CustomEvent("zr_popover");

    function asyncLoad(){

      var s = document.createElement("script");

      s.type = "text/javascript";

      s.async = true;

      s.src = "https://wifa.st/static/popover/widget_popover_c.min.js?id=09f768b5-e311-494b-a29e-f6cb5e1df65f&w=600&h=941";

      var embedder = document.getElementById("zr-57c711b0f4c47f000a94030f");

      embedder.parentNode.insertBefore(s, embedder);

    }

    if (window.attachEvent) window.attachEvent("zr_popover", asyncLoad);

    else window.addEventListener("zr_popover", asyncLoad, false);

  })();

</script>`

**Comment by rickyferrer** [comment]
The previous comment contains code for an interstitial. We'll also need to replace the email signup form on the website as well.

**Comment by rickyferrer** [comment]
https://www.zenreach.com/
Username: jessica@turnthetableshospitality.com
Password: Deskjet12!

**Comment by xtinarees** [comment]
smoke dallas - returning page not found. 
http://smokerestaurant.com/dallas/

**Comment by rickyferrer** [comment]
I tried republishing. Try this? `<form action="https://my.zenreach.com/api/widgets/submit_customer/" method="post" enctype="application/x-www-form-urlencoded">
<input type="hidden" name="business_id" value="57c711cdf4c47f000a940311"/>
<input type="hidden" name="tags" value="smoke dallas"/>
<p>STAY IN TOUCH</p>
<p>Enter your email below for updates, promotions, and special offers</p>
<label>Email*</label>
<input type="text" name="email" placeholder="hello@email.com"/>
<button type="submit">SIGN UP</button>
</form>`

**Comment by xtinarees** [comment]
That worked!
