### ISSUE TITLE
All Sites: Breaking News banner

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/Turn-The-Table#45]

**Comment by xtinarees** [comment]
@rickyferrer will this show up on the homepage? will different parts of the site need different messages (for example, would Bolsa Mercado need a breaking news banner while Bolsa does not).

**Comment by rickyferrer** [comment]
Yes, we will need different ones for different sites. Bolsa will have different news than Bolsa Mercado.

**Comment by xtinarees** [comment]
what about the homepage?

**Comment by rickyferrer** [comment]
Correct.
