### ISSUE TITLE
All Sites: Instagram feed

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/Turn-The-Table#46]
like we did for Sweet Loren's

**Comment by xtinarees** [comment]
@rickyferrer does this need to support 2 different feeds on one site (ex: smoke plano vs smoke dallas)?

**Comment by rickyferrer** [comment]
Separate.

**Comment by xtinarees** [comment]
@rickyferrer this is live. I could only find instagram accounts for theodore and bolsa, so I added those their respective sites. Its a little confusing to set up so let me know if you have any questions.
