### ISSUE TITLE
BOLSA: Safair issues with Toggle slideshow

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/Turn-The-Table#47]
from client: _We are still having issues with Loma Linda’s photos in Safari. I am on 9.1.2. and they aren’t rotating. Justo is on 9.0.2 and they aren’t showing up at all, but it is intermittent. In Chrome, everything works fine. On Safari on the iPhone, it also doesn’t rotate and I am on the most recent version of the software, but it works fine for Justo._

**Comment by xtinarees** [comment]
@rickyferrer I was not able to duplicate this issue. I tried using a simulator with the settings provided, but the slideshow worked correctly. It also worked on safari on my phone. I am going to update the flexslider library and maybe that will fix the issue, but not sure what to do otherwise.

**Comment by rickyferrer** [comment]
OK, thanks for looking into it.
